### ISSUE TITLE
Support for fractional (1/4 and 1/2) minimum compute sizes

### ISSUE THREAD

**Issue by asterikx** [kislerdm/neon-sdk-go#15]
Currently, it is not possible to create projects or endpoints with fractional compute sizes, as the autoscaling limits are typed as `int32`.

https://github.com/kislerdm/neon-sdk-go/blob/df8427ac7dfea29eeb45a34aae7bf6e952df5a27/sdk.go#L1097-L1098

Changing them to `float32` is also required for https://github.com/kislerdm/terraform-provider-neon/issues/32.

**Comment by kislerdm** [comment]
@asterikx Hey Erik! Thanks for submitting the issue. I commit to release a new version which will include the fix according to the up-to-date version of the Neon API.
