### ISSUE TITLE
Please update OpenAPI schema

### ISSUE THREAD

**Issue by nikitakalyanov** [kislerdm/neon-sdk-go#9]
Hi @kislerdm ! Thank you for your project. Recently, we had an API update. One change about the project quota could break this SDK - now the `quota` field is nested in the `settings` field. I tried to update the schema and regenerate the code, but it failed because of the new project pagination. I am still trying to get to the root cause. So, opening this issue to remember. Let me know if I can help

**Comment by kislerdm** [comment]
@nikitakalyanov Hey Nikita! Thanks a lot for this feedback. I plan for execution on ASAP basis.
